### ISSUE TITLE
UI/UX Design

### ISSUE THREAD

**Issue by SazidAhmed** [Techminate/TNBC-POS#1]
Design of following pages : 
login, 
register, 
password reset, 
user list, 
user role-permission,
Dashboard, 
product unit, 
Product create/update, 
Product list, 
product details, 
POS interface, 
system settings, 
QR code generation, 
transaction explorer, 
user profile, 
general sales report 
TNBC sales report, 
data backup and import/export page.

**Comment by sazid12** [comment]
ok <33
